### ISSUE TITLE
.ignore Plugin causes too many Threads hang / crash dump in phpstorm

### ISSUE THREAD

**Issue by alpham8** [hsz/idea-gitignore#390]
Hi,

I encountered an issue with your newest version of your plugin. I think since the last .ignore update it causes phpstorm randomly after maximazing the IDE window again an too many Threads hang issue or better saying an thread crash dump log.
This is especially feelable, when you maximize phpstorm again and it hangs for at least 3 seconds. In very hard cases I also needed to kill the IDE process completely. I am not sure which SIGTERM Signal it was exactly when I needed to kill it by hand, because I am / was using phpstorm under Mac OS X and I did it graphically.
After getting in touch with the JetBrains support, we found out, that it is clearly addressable to your plugin. After disabling it and working as usually two days without it, everything worked fine - no hangs.

Here is the original JetBrains board topic to it: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000467630-phpstorm-hangs-sometimes-when-maximizing-the-IDE-again

And in the attachments you can find the logging files and crash dump files from about two days.

Thank you very much for creating awesome openSource Software! :-)

I hope this helps to resolve the problem, so that I can use the plugin again on my Mac.

PS: I was using phpstorm 2017.1.4 as this issue appeared. But I don't think that this changes anything on the issue itself, because your plugin wasn't been updated since then. Also, I didn't update phpstorm during the whole JetBrains support request. So, I used from the beginning until the end only phpstorm 2017.1.4 on MacOS Sierra Version 10.12.5

[threadDumps-2days.zip](https://github.com/hsz/idea-gitignore/files/1164692/threadDumps-2days.zip)

[idea.log.zip](https://github.com/hsz/idea-gitignore/files/1164693/idea.log.zip)

**Comment by hsz** [comment]
@alpham8 Thank you for this report!

With the v2.0.0 version released just right now I have fixed a lot of the threading issues. Can you please verify if it resolves your issues?

**Comment by BramDriesen** [comment]
No it did not solve it. My PHPstorm can barely handle the latest update. Constantly lagging and getting memory dumps. I'm uninstalling the plugin for now, having too many issues with it at the moment.

**Comment by hsz** [comment]
With #415 I have resolved couple of the performance issues. I'll release it in a few days in v2.1.0

**Comment by Ig0r-M** [comment]
@hsz got version 2.6.2 and i can confirm that on my machine above problems persist, it might not be identical but i am sure it's current plugin as it hangs only when working with `.gitignore` file. Plugin disabling/removal make this problem disappear. PhpStorm version is `2018.1.6`

**Comment by abunch** [comment]
Same as @Ig0r-M but I'm on 2018.2.5.  Editing the .gitignore file hangs PhpStorm, disabling the plugin clears the problem up.
