### ISSUE TITLE
Ignored items in my profile ~/.gitignore_global are no more grayed in the Project view

### ISSUE THREAD

**Issue by jcdevil** [hsz/idea-gitignore#453]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
With previous version, the excluded items defined in my profile ~/.gitignore_global when grayed in the Project view.
It's no more the case with this new version (2.1.1)

### Steps to Reproduce

1. Select a file in your project
2. Use the `Add to .gitignore file` contextual option to add this file in the .gitignore file
3. While editing the .gitignore file, slected the added line and cut it to the clipboard
4. Lower, in the `Outer ignore rules`, edit your profile ~/.gitignore_global
5. Paste the line in the file and save it

**Expected behavior:** 
I expect the file to be grayed in the Project treeview, be it in the .gitignore file or in my ~/.gitignore_global file

**Actual behavior:** _What actually happens_
In the Project treeview, the file was grayed when the line was in the .gitignore file
Then cutting this line and putting the profile ~/.gitignore_global file make the file appear as an "not-ignore" file in the Project treeview

**Reproduces how often:**
Systematically

### Versions

**Plugin:** 
2.1.1

**IDE:** 
PyCharm Community Edition 2017.2.1

**OS:** 
macOS Sierra 10.12.6

### Additional Information
None
Thx for your support ;)

**Comment by finnef** [comment]
Similar problem with PhpStorm:

Plugin:
2.1.1
IDE:
PhpStorm 2017.2.1
OS:
macOS Sierra 10.12.6

When opening a project the project view does not show ignored files from my toplevel .gitignore. Editing and saving the .gitignore file makes the ignored files show in gray again.

**Comment by fernakano** [comment]
I had this issue after updating, but after disabling and enabling the plugin again it worked fine for me.
Looks like it is something with the update.

Ignore Plugin Version: 2.1.1

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
Mac OS X 10.12.6

**Comment by jcdevil** [comment]
OK, thx for this info..
Unfortunately this workaround does not work for me (although I disabled the plugin / restarted PyCharm / enabled plugin / restarted PyCharm) :(

**Comment by hsz** [comment]
Thanks for the report!
Indeed there was a problem because `.gitignore_global` filename doesn't math `.gitignore` which is assigned to the IgnoreFileType. I've fixed it - filename specified as a global gitignore file will be assigned to the proper filetype since now.

**Comment by hsz** [comment]
Fix is available in **v2.2.0-RC1** in EAP channel.

**Comment by jcdevil** [comment]
Thx for the fix !
Regards

**Comment by StevenMapes** [comment]
I've noticed this bug is back in version 2.2.1 when using Pycharm 2017.2.3

**Comment by jcdevil** [comment]
Yep agreed : same for me :(

**Comment by dAnjou** [comment]
Bug is still back in version 2.2.2 :confused:

PyCharm 2017.2.3 Build #PY-172.3968.37, built on September 1, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.5-200.fc26.x86_64

**Comment by hsz** [comment]
Indeed there was a problem with caching those files - it's fixed and will be released with v2.3.0

**Comment by dAnjou** [comment]
For some reason it still doesn't seem to be working with version 2.3.2:
![pycharm_ignore_plugin_bug](https://user-images.githubusercontent.com/117147/33137195-948aed60-cfa7-11e7-8783-40af2c3d5e5f.png)
