### ISSUE TITLE
Error on opening .gitignore file

### ISSUE THREAD

**Issue by Ionaru** [hsz/idea-gitignore#470]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

After updating the plugin to 2.0.0 today, I opened the .gitignore file in my project and the plugin threw an error.

```java
null
java.lang.NullPointerException
	at mobi.hsz.idea.gitignore.util.MatcherUtil.match(MatcherUtil.java:84)
	at mobi.hsz.idea.gitignore.util.Glob$1.visitFile(Glob.java:126)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:132)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:272)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at mobi.hsz.idea.gitignore.util.Glob.find(Glob.java:140)
	at mobi.hsz.idea.gitignore.util.Glob.findOne(Glob.java:69)
	at mobi.hsz.idea.gitignore.daemon.IgnoreDirectoryMarkerProvider.getLineMarkerInfo(IgnoreDirectoryMarkerProvider.java:71)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:189)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Steps to Reproduce

1. Have existing project with .gitignore file
2. Open the file

**Expected behavior:** No error

**Actual behavior:** Error is thrown

**Reproduces how often:** Only happened once so far.

### Versions

**Plugin:** 

```
2.2.0
```

**IDE:** 

```
IntelliJ IDEA 2017.2.3
```

**OS:** 

```
Ubuntu 17.04
```

**Comment by hsz** [comment]
@Ionaru Thanks for reporting. To be honest - it's insane that this still happens. I covered this method with as many null checks as possible, but somehow it still has a problem with NPE.

Sorry for that - if it will happen again - let me know and I'll speed up the next release.

**Comment by n1k0laj** [comment]
I have the same issue. WebStorm 2017.2.3 Windows 10 10.0.

**Comment by FedeMarshall** [comment]
Same issue here.
plugin version 2.2.0
WebStorm 2017.2.3
Windows 10

**Comment by binzcodes** [comment]
+1 WebStorm 2017.2.3 latest version of plugin OSX

**Comment by hsz** [comment]
I have just published `v2.2.1-RC1` which is available in (Early Access Preview repository channel)[https://github.com/hsz/idea-gitignore#early-access-preview-repository-channel] or for (manual installation)[https://github.com/hsz/idea-gitignore/releases/tag/v2.2.1-RC1]

Can you please check if this issue is resolved for you?

**Comment by cwilli34** [comment]
This resolved the error for me, but the file coloring is still not working.  And I get warning on every line that states " '...' is never used more...".  

This is in a .gitignore file.

Plugin:
```
2.2.1-RC1
```

IDE:
```
Rider 2017.2 EAP
```

OS:
```
Windows 10
```

**Comment by Omcsesz** [comment]
Same for me.
![default ignore plugin](https://user-images.githubusercontent.com/1839739/30416232-b318fc02-992b-11e7-845b-10c2c3ac3267.png)
Android Studio 2.3.3, Win 7 64 bit
